name: 'Build NextJS App'

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install npm dependencies
        run: npm install
      - name: Build
        run: npm run build
